#!/usr/bin/env bash

echo "Beeginning Purge"

echo "Removing LXDE and all files related"
apt remove lxde* lxpanel pipanel openbox* obconf lightdm --purge -y
wait
echo "Removing any undepended packages"
apt autoremove -y
wait
